on:
    push:
      branches: main
  
  name: Render
  
  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
          
        - name: Setup Quarto
          uses: quarto-dev/quarto-actions/setup@v2
        #   with:
        #     tinytex: true
  
        - name: Quarto version
          run: |
            quarto --version
  
        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}